Dev/hygg
Genshin-and-board-game-group/backend pull request #10
Opened 2022-11-28 06:53 UTC by FZUchy2001

2022-11-30 06:54 UTC, everlasting2002 approved these changes

2022-12-02 07:25 UTC, kernelbin commented on backend/backend/HttpSendRecv.h
> +    BOOL bBecomeFairy; // become Fairy
那个，出于一些设计考虑我希望通信的部分和游戏本身尽可能互相独立开（因为后期有可能加入更多通信方式）。所以我个人不太希望在这里放更多有关游戏本身的数据，只在这里放了 `pRoom` 和 `WaitingIndex` / `PlayingIndex`。

此外访问这些涉及游戏的数据需要先获取 `pRoom` 中的锁，放在这里可能容易忘记上锁一事。

当然这么写没什么问题，不过....如果需要存一些数据，我希望可以改为放在 `PGAME_ROOM` 中（比如开一个 `bBecomeFairy[ROOM_PLAYER_MAX]` 数组，存放每个人的对应信息）然后通过 `PlayingIndex` 来访问对应对应玩家的数组元素。

另外，记得在游戏重新开局的时候重新初始化必要的数据（见 `StartGame` 函数）否则房间内还会保留着上一局的数据

2022-12-13 15:31 UTC, kernelbin requested changes

2022-12-13 15:31 UTC, kernelbin commented on backend/backend/RoomManager.c
> +                        HINT[HINT_CNT++] = (HINTLIST){  pRoom -> PlayingList[j]. GameID, HINT_BAD};
为什么这里的空格这么奇怪x

2022-12-13 15:31 UTC, kernelbin commented on backend/backend/RoomManager.c
> +        return ReplyPlayerSelectTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
这里以及其他几处判断 Game_Win 的地方似乎有一点点问题
可能会存在有一个线程正在修改 Game_Win 时在这些地方读取判断 Game_Win 进而造成异常
应该在获取了锁之后，放在 __try 保护的代码段里进行判断
（其实是我变量名起了之后代码写着写着含义改变了，PlayerListLock 现在可以考虑重命名为 RoomLock 了...？）

2022-12-13 15:31 UTC, kernelbin commented on backend/backend/RoomManager.c
> +        // TODO: fix wrong count
TODO 可以移除掉了

2022-12-13 15:31 UTC, kernelbin commented on backend/backend/RoomManager.c
> +        // TODO: fix wrong count
TODO可以移走了

2022-12-14 16:23 UTC, kernelbin commented on backend/backend/RoomManager.c
> +                ++pRoom->Game_Win;
pRoom 内的数据并不会随着游戏新开一把而重置，这些字段可能需要在 StartGame 时重新初始化

2022-12-14 16:26 UTC, kernelbin commented on backend/backend/RoomManager.c
> +            return ReplyPlayerSelectTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
最好还是写成用 __leave 来离开作用域
```suggestion
        if (pRoom->Game_Win>=3)
        {
            bSuccess = ReplyPlayerSelectTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
            __leave;
        }
```

2022-12-14 16:27 UTC, kernelbin commented on backend/backend/RoomManager.c
> +            return ReplyPlayerConfirmTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
```suggestion
        if (pRoom->Game_Win >= 3)
        {
            bSuccess = ReplyPlayerConfirmTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
            __leave;
        }
```

2022-12-14 16:29 UTC, kernelbin commented on backend/backend/RoomManager.c
> +            return ReplyPlayerVoteTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
```suggestion
        if (pRoom->Game_Win >= 3)
        {
            bSuccess = ReplyPlayerVoteTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
            __leave;
        }
```

2022-12-14 16:30 UTC, kernelbin commented on backend/backend/RoomManager.c
> +            return ReplyPlayerConductMission(pConnInfo, FALSE, "Good guys have win 3 rouonds.");
```suggestion
        if (pRoom->Game_Win >= 3)
        {
            bSuccess = ReplyPlayerConductMission(pConnInfo, FALSE, "Good guys have win 3 rouonds.");
            __leave;
        }
```

2022-12-14 16:35 UTC, kernelbin commented on backend/backend/RoomManager.c
> +            if (pRoom->VotedIDList[i].ID == pConnInfo->PlayingIndex) {
是不是 这里 ID 和 Index 也写混了x

2022-12-14 16:36 UTC, kernelbin commented on backend/backend/RoomManager.c
> +        pRoom->VotedIDList[pRoom->VotedCount++] = (VOTELIST){ pConnInfo->PlayingIndex ,bVote };
是不是 这里 ID 和 Index 也写混了x
发送的话应该是始终发 ID 的

2022-12-14 16:39 UTC, kernelbin commented on backend/backend/RoomManager.h
> +    UINT TeamMemberid[ROOM_PLAYER_MAX];
虽然但是 为什么这个数组里明明存着的是 Index 变量名却是 ID （（（

2022-12-14 16:42 UTC, kernelbin commented on backend/backend/RoomManager.c
> +            if (pRoom->DecidedIDList[i] == pConnInfo->PlayingIndex) {
这里是不是 ID 和 Index 写混了啊x

2022-12-14 16:49 UTC, kernelbin commented on backend/backend/RoomManager.c
> +        return ReplyPlayerFairyInspect(pConnInfo, FALSE, "The room doesn't have the fairy.");
应该放入 __try 中执行

2022-12-14 16:49 UTC, kernelbin commented on backend/backend/RoomManager.c
> +                __leave;
这些发送消息的函数如果返回 FALSE 说明出现了比较严重的错误，比如内存分配失败（可能由内存不足导致）等，应该也在这里返回 FALSE（把 bSuccess 标成 FALSE，然后 __leave），让调用这个函数的函数知道这里出现了严重错误，进而可以进一步进行清理工作。
其他几处类似的需要完善的地方我没有在review里一一标出来了（比如紧挨着的下面几行）

2022-12-18 13:52 UTC, FZUchy2001 commented on backend/backend/RoomManager.h
> +    UINT TeamMemberid[ROOM_PLAYER_MAX];
这个存ID的

2022-12-18 13:52 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +                ++pRoom->Game_Win;
已经重置

2022-12-18 13:59 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +            if (pRoom->DecidedIDList[i] == pConnInfo->PlayingIndex) {
确实写混了

2022-12-18 14:00 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +        pRoom->VotedIDList[pRoom->VotedCount++] = (VOTELIST){ pConnInfo->PlayingIndex ,bVote };
已改

2022-12-18 14:00 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +            if (pRoom->VotedIDList[i].ID == pConnInfo->PlayingIndex) {
已改

2022-12-18 14:00 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +            return ReplyPlayerConductMission(pConnInfo, FALSE, "Good guys have win 3 rouonds.");
写成用 __leave 来离开作用域

2022-12-18 14:00 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +            return ReplyPlayerVoteTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
写成用 __leave 来离开作用域

2022-12-18 14:00 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +            return ReplyPlayerConfirmTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
写成用 __leave 来离开作用域

2022-12-18 14:00 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +            return ReplyPlayerSelectTeam(pConnInfo, FALSE, "Good guys has win 3 rouonds.");
写成用 __leave 来离开作用域

2022-12-18 14:00 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +                __leave;
全加__leave了

2022-12-18 14:00 UTC, FZUchy2001 commented on backend/backend/RoomManager.c
> +        return ReplyPlayerFairyInspect(pConnInfo, FALSE, "The room doesn't have the fairy.");
已放入 __try 中执行

2022-12-18 15:28 UTC, kernelbin approved these changes

2022-12-18 15:29 UTC, merged